<a href="https://colab.research.google.com/github/Terence0408/Teach_code/blob/master/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [0]:
import numpy as np

#### List to numpy array

In [0]:
xx = [1,2,3,4,5,6,7,8,9,10,11,12]

nparray = np.array(xx, dtype=np.float32)
nparray

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)

In [0]:
nparray.shape

(12,)

#### Reshape

In [0]:
nparray = nparray.reshape((4, 3))
nparray

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

#### Create numpy array

In [0]:
zeroarray = np.zeros((4, 3), dtype=np.float32)
zeroarray

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [0]:
onearray = np.ones((4, 3), dtype=np.float32)
onearray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

#### Array 矩陣處理

##### Select and change value

###### Elements

In [0]:
nparray[0,0] = 0
nparray[1,1] = 0
nparray[2,2] = 0

nparray

array([[ 0.,  2.,  3.],
       [ 4.,  0.,  6.],
       [ 7.,  8.,  0.],
       [10., 11., 12.]], dtype=float32)

###### Subarray

In [0]:
nparray[0:3,0:3]

array([[0., 2., 3.],
       [4., 0., 6.],
       [7., 8., 0.]], dtype=float32)

In [0]:
nparray[0:3,0:3]=[[1,2,3],
                  [4,5,6],
                  [7,8,9]]
nparray

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

##### Arithmetic

In [0]:
np.add(nparray, 2)

array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]], dtype=float32)

In [0]:
np.add(nparray, onearray)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.],
       [11., 12., 13.]], dtype=float32)

In [0]:
np.multiply(nparray, nparray)

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.],
       [ 49.,  64.,  81.],
       [100., 121., 144.]], dtype=float32)

In [0]:
np.mod(nparray, 2)

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]], dtype=float32)

##### Concatenate

In [0]:
np.concatenate((nparray, nparray), axis=1)


array([[ 1.,  2.,  3.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  4.,  5.,  6.],
       [ 7.,  8.,  9.,  7.,  8.,  9.],
       [10., 11., 12., 10., 11., 12.]], dtype=float32)

In [0]:
np.concatenate((nparray, nparray), axis=0)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

##### Aggregate

##### 整體

In [0]:
np.median(nparray)

6.5

In [0]:
nparray.sum()

78.0

In [0]:
nparray.max()

12.0

##### 各行列統計量

In [0]:
nparray.max(axis=0)

array([10., 11., 12.], dtype=float32)

In [0]:
nparray.max(axis=1)

array([ 3.,  6.,  9., 12.], dtype=float32)

In [0]:
nparray.argmax(axis=0)

array([3, 3, 3])

In [0]:
nparray.argmax(axis=1)

array([2, 2, 2, 2])

# SQL

#### 連接到資料庫

##### 連接到 MySQL

In [0]:
!pip install -q mysql-python

     |████████████████████████████████| 112kB 5.0MB/s 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


In [0]:
import MySQLdb
conn = MySQLdb.connect(host="localhost", db="db_name", user="db_user", passwd="db_pass")
cur = conn.cursor()

ModuleNotFoundError: ignored

##### 連接到 postgreSQL

In [0]:
!pip install -q psycopg2

In [0]:
import psycopg2
conn = psycopg2.connect("host=localhost dbname=example user=postgres")
conn.autocommit = True 
cur = conn.cursor()

/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


OperationalError: ignored

##### 連接到 sqlite

In [0]:
import sqlite3
conn = sqlite3.connect('dbname=example.db')
cur = conn.cursor()

##### 關閉連接
```
cur.close()
conn.close()
```

#### 從 python 送指令給 SQL database
```
cur.execute(指令文字)
conn.commit()
```

#### CREATE
放新資料的位置


*   TABLE: 以實體存在
*   VIEW: 以指令存在，只有執行時才會跑，關閉 DB 就自動刪除



In [0]:
cur.execute('''Drop Table IF Exists old_A;''')
conn.commit()

cur.execute('''CREATE TABLE old_A
               (id      serial, 
                area    text, 
                age     double precision, 
                sex     CHAR(10));''')
conn.commit()

In [0]:
try:
   cur.execute('''CREATE TABLE old_B
                  (id      serial, 
                   income  double precision);''')
   conn.commit()
except:
   print("table old_B already exists")

table old_B already exists


##### Insert data

In [0]:
cur.execute("""INSERT INTO old_A 
               VALUES (1, 'S',  5,  'male');""")
conn.commit()

In [0]:
cur.execute("""INSERT INTO old_A (id, area, sex) 
               VALUES (2, 'N',     'female');""")
conn.commit()

In [0]:
cur.execute("""INSERT INTO old_A (id, area, age, sex) 
               VALUES (3, 'E', 30,   'male'),
                      (4, 'S', 10, 'female'),
                      (5, 'N', 60,   'male'),
                      (6, 'E', 90, 'female');""")
conn.commit()

In [0]:
xx = [["1","20"],["4","10"],["5","30"],["7","40"],["8","11"],["19","20"]]

for i in range(0,len(xx)):
    query  = "INSERT INTO old_B (id, income) "
    query += "VALUES ("+",".join(xx[i])+");"
    print(query)

    cur.execute(query)
    conn.commit()

INSERT INTO old_B (id, income) VALUES (1,20);
INSERT INTO old_B (id, income) VALUES (4,10);
INSERT INTO old_B (id, income) VALUES (5,30);
INSERT INTO old_B (id, income) VALUES (7,40);
INSERT INTO old_B (id, income) VALUES (8,11);
INSERT INTO old_B (id, income) VALUES (19,20);


##### Update data

In [0]:
query  = "UPDATE old_A "
query += "SET age = 20 "
query += "WHERE id = 2;"

cur.execute(query)
conn.commit()

#### SELECT  
選取需要的變數

##### Python 內看選取結果要用 .fetchall()


> 欄位名稱在 cur.description



In [0]:
query  = "SELECT * "
query += "FROM old_A;"

cur.execute(query)
conn.commit()

In [0]:
query  = "SELECT * "
query += "FROM old_A;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'area', 'age', 'sex']
(1, 'S', 5.0, 'male')
(2, 'N', 20.0, 'female')
(3, 'E', 30.0, 'male')
(4, 'S', 10.0, 'female')
(5, 'N', 60.0, 'male')
(6, 'E', 90.0, 'female')


##### 欄位別名 & 表格別名 
``` 
SELECT 表格別名.欄位 as 欄位別名
FROM 表格名 as 表格別名; 
```

In [0]:
query  = "SELECT t1.id, t1.area "
query += "FROM old_A as t1;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'area']
(1, 'S')
(2, 'N')
(3, 'E')
(4, 'S')
(5, 'N')
(6, 'E')


##### 欄位 if-else-then 條件
```
CASE WHEN 條件1 THEN 結果1
     .........
     WHEN 條件N THEN 結果N
     ELSE 結果X
     END as 新欄位名稱
```

In [0]:
query  = "SELECT t1.id, t1.sex, " 
query += "       Case When t1.sex = 'female' then 0 " 
query += "            When t1.sex =   'male' then 1 "
query += "            ELSE NULL "
query += "       END as sex_n "
query += "FROM old_A as t1;" 

cur.execute(query) 
results = cur.fetchall() 

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'sex', 'sex_n']
(1, 'male', 1)
(2, 'female', 0)
(3, 'male', 1)
(4, 'female', 0)
(5, 'male', 1)
(6, 'female', 0)


#### WHERE 
條件式篩選資料，ex. 只處理年齡 > 60

In [0]:
query  = "SELECT t1.id, t1.area, t1.age, t1.sex "
query += "FROM old_A as t1 "
query += "WHERE t1.area = 'S' or t1.area = 'N';"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'area', 'age', 'sex']
(1, 'S', 5.0, 'male')
(2, 'N', 20.0, 'female')
(4, 'S', 10.0, 'female')
(5, 'N', 60.0, 'male')


In [0]:
query  = "SELECT t1.id, t1.area, t1.age, t1.sex "
query += "FROM old_A as t1 "
query += "WHERE t1.area in ('S', 'N');"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'area', 'age', 'sex']
(1, 'S', 5.0, 'male')
(2, 'N', 20.0, 'female')
(4, 'S', 10.0, 'female')
(5, 'N', 60.0, 'male')


#### FROM
從那些表格得到資料，牽涉到 JOIN

##### 用 WHERE 給條件


> 缺：計算較慢



In [0]:
query  = "SELECT t1.id, t1.age, t1.sex, t2.income "
query += "FROM old_A as t1, old_B as t2 "
query += "WHERE t1.id = t2.id;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'age', 'sex', 'income']
(1, 5.0, 'male', 20.0)
(1, 5.0, 'male', 20.0)
(1, 5.0, 'male', 20.0)
(4, 10.0, 'female', 10.0)
(4, 10.0, 'female', 10.0)
(4, 10.0, 'female', 10.0)
(5, 60.0, 'male', 30.0)
(5, 60.0, 'male', 30.0)
(5, 60.0, 'male', 30.0)


##### 用 JOIN 給條件

> 在 Google 圖片下："SQL JOIN" 


In [0]:
query  = "SELECT t1.id, t1.age, t1.sex, t2.income "
query += "FROM old_A as t1 INNER JOIN old_B as t2 on t1.id = t2.id;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'age', 'sex', 'income']
(1, 5.0, 'male', 20.0)
(1, 5.0, 'male', 20.0)
(1, 5.0, 'male', 20.0)
(4, 10.0, 'female', 10.0)
(4, 10.0, 'female', 10.0)
(4, 10.0, 'female', 10.0)
(5, 60.0, 'male', 30.0)
(5, 60.0, 'male', 30.0)
(5, 60.0, 'male', 30.0)


#### GROUP BY 
分群計算，ex. 計算總和

In [0]:
query  = "SELECT t1.area, SUM(t1.age), AVG(t1.age) as avg_age, count(*) as count "
query += "FROM old_A as t1 "
query += "GROUP BY t1.area;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['area', 'SUM(t1.age)', 'avg_age', 'count']
('E', 120.0, 60.0, 2)
('N', 80.0, 40.0, 2)
('S', 15.0, 7.5, 2)


#### HAVING
篩選分群計算後的結果


> 必須與 GROUP BY 搭配



In [0]:
query  = "SELECT t1.area, SUM(t1.age), AVG(t1.age) as avg_age, count(*) as count "
query += "FROM old_A as t1 "
query += "GROUP BY t1.area "
query += "HAVING avg_age >=40;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['area', 'SUM(t1.age)', 'avg_age', 'count']
('E', 120.0, 60.0, 2)
('N', 80.0, 40.0, 2)


#### ORDER BY
排序資料

In [0]:
query  = "SELECT t1.area, SUM(t1.age), AVG(t1.age) as avg_age, count(*) as count "
query += "FROM old_A as t1 "
query += "GROUP BY t1.area "
query += "HAVING avg_age >=40 "
query += "ORDER BY avg_age;"

cur.execute(query)
results = cur.fetchall()

cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['area', 'SUM(t1.age)', 'avg_age', 'count']
('N', 80.0, 40.0, 2)
('E', 120.0, 60.0, 2)


#### 另一種送指令方式
> 用類似 python 處理字串的方式查詢值或給值



In [0]:
# Ex.       "INSERT INTO old_B (id, income) VALUES (1,20);"
cur.execute("INSERT INTO old_B (id, income) VALUES (?, ?);", [1,20])
conn.commit()

cur.execute("SELECT * FROM old_B")
results = cur.fetchall()
cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

['id', 'income']
(1, 20.0)
(4, 10.0)
(5, 30.0)
(7, 40.0)
(8, 11.0)
(19, 20.0)
(1, 20.0)
(4, 10.0)
(5, 30.0)
(7, 40.0)
(8, 11.0)
(19, 20.0)
(1, 20.0)
(4, 10.0)
(5, 30.0)
(7, 40.0)
(8, 11.0)
(19, 20.0)
(1, 20.0)


# Pandas

In [0]:
import pandas as pd

#### Numpy -> Pandas

In [0]:
Data = np.asarray([[1, 'S',  5.0,   'male'],
                   [2, 'N', 20.0, 'female'],
                   [3, 'E', 30.0,   'male'],
                   [4, 'S', 10.0, 'female'],
                   [5, 'N', 60.0,   'male'],
                   [6, 'E', 90.0, 'female']])
Data

array([['1', 'S', '5.0', 'male'],
       ['2', 'N', '20.0', 'female'],
       ['3', 'E', '30.0', 'male'],
       ['4', 'S', '10.0', 'female'],
       ['5', 'N', '60.0', 'male'],
       ['6', 'E', '90.0', 'female']], dtype='<U21')

In [0]:
df = pd.DataFrame(data=Data,                                          # values
                  columns= ['id', 'area', 'age', 'sex'],              # column names
                  index  = ['1st', '1st','2nd','2nd','3rd','3rd'])    # row index
df                      

id area   age     sex
1st  1    S   5.0    male
1st  2    N  20.0  female
2nd  3    E  30.0    male
2nd  4    S  10.0  female
3rd  5    N  60.0    male
3rd  6    E  90.0  female

#### Pandas <-> SQL

In [0]:
df = pd.read_sql_query("SELECT * FROM old_A;", con=conn)
df

In [0]:
try:
    df.to_sql('users', con=conn)
except:
    print("Table 'users' already exists.")

cur.execute("SELECT * FROM users")
results = cur.fetchall()
cols = [i[0] for i in cur.description]
print(cols)  
for result in results:
    print(result)

Table 'users' already exists.
['index', 'id', 'area', 'age', 'sex']
(0, 1, 'S', 5.0, 'male')
(1, 2, 'N', 20.0, 'female')
(2, 3, 'E', 30.0, 'male')
(3, 4, 'S', 10.0, 'female')
(4, 5, 'N', 60.0, 'male')
(5, 6, 'E', 90.0, 'female')


#### Pandas <-> CSV

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')  
df.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [0]:
df.to_csv("BostonHousing.csv")

#### Pivot table

In [0]:
pd.pivot_table(df,
               index=['rad'], 
               values=['age', 'crim'])

age       crim
rad                      
1    45.025000   0.036029
2    64.770833   0.083285
3    49.310526   0.097359
4    60.841818   0.393903
5    69.223478   0.687792
6    60.142308   0.150054
7    40.141176   0.150399
8    67.350000   0.371410
24   89.805303  12.759291

In [0]:
pd.pivot_table(df,
               index=['chas','rad'],
               values=['age', 'crim'])

age       crim
chas rad                      
0    1    46.089474   0.037135
     2    64.770833   0.083285
     3    48.902778   0.094087
     4    60.681373   0.409490
     5    67.475962   0.622514
     6    60.142308   0.150054
     7    40.141176   0.150399
     8    63.994737   0.345052
     24   89.731452  13.209833
1    1    24.800000   0.015010
     3    56.650000   0.156265
     4    62.887500   0.195176
     5    85.745455   1.304961
     8    80.100000   0.471570
     24   90.950000   5.775886

In [0]:
pd.pivot_table(df,
               index=['rad'], 
               columns=['chas'], 
               values=['age'])

age           
chas          0          1
rad                       
1     46.089474  24.800000
2     64.770833        NaN
3     48.902778  56.650000
4     60.681373  62.887500
5     67.475962  85.745455
6     60.142308        NaN
7     40.141176        NaN
8     63.994737  80.100000
24    89.731452  90.950000

In [0]:
pd.pivot_table(df,
               index=['rad'], 
               columns=['chas'], 
               values=['age'],
               aggfunc=[np.sum,np.mean])

sum              mean           
          age               age           
chas        0      1          0          1
rad                                       
1       875.7   24.8  46.089474  24.800000
2      1554.5    NaN  64.770833        NaN
3      1760.5  113.3  48.902778  56.650000
4      6189.5  503.1  60.681373  62.887500
5      7017.5  943.2  67.475962  85.745455
6      1563.7    NaN  60.142308        NaN
7       682.4    NaN  40.141176        NaN
8      1215.9  400.5  63.994737  80.100000
24    11126.7  727.6  89.731452  90.950000

In [0]:
pd.pivot_table(df,
               index=['rad'], 
               columns=['chas'], 
               values=['age'],
               aggfunc=[np.sum,np.mean],
               fill_value=0)

sum              mean           
          age               age           
chas        0      1          0          1
rad                                       
1       875.7   24.8  46.089474  24.800000
2      1554.5    0.0  64.770833   0.000000
3      1760.5  113.3  48.902778  56.650000
4      6189.5  503.1  60.681373  62.887500
5      7017.5  943.2  67.475962  85.745455
6      1563.7    0.0  60.142308   0.000000
7       682.4    0.0  40.141176   0.000000
8      1215.9  400.5  63.994737  80.100000
24    11126.7  727.6  89.731452  90.950000

In [0]:
pd.pivot_table(df,
               index=['rad'], 
               columns=['chas'], 
               values=['age'],
               aggfunc=[np.sum,np.mean],
               fill_value='X',
               margins=1)

sum                        mean                    
          age                         age                    
chas        0       1      All          0        1        All
rad                                                          
1       875.7    24.8    900.5  46.089474     24.8  45.025000
2      1554.5       X   1554.5  64.770833        X  64.770833
3      1760.5   113.3   1873.8  48.902778    56.65  49.310526
4      6189.5   503.1   6692.6  60.681373  62.8875  60.841818
5      7017.5   943.2   7960.7  67.475962  85.7455  69.223478
6      1563.7       X   1563.7  60.142308        X  60.142308
7       682.4       X    682.4  40.141176        X  40.141176
8      1215.9   400.5   1616.4  63.994737     80.1  67.350000
24    11126.7   727.6  11854.3  89.731452    90.95  89.805303
All   31986.4  2712.5  34698.9  67.911677     77.5  68.574901

#### 資料選擇與篩選





In [0]:
df_p = pd.pivot_table(df,
                      index=['rad'],
                      values=['age','crim','zn'],
                      margins=1)
df_p

age       crim         zn
rad                                 
1    45.025000   0.036029  39.900000
2    64.770833   0.083285  20.416667
3    49.310526   0.097359  16.381579
4    60.841818   0.393903  14.731818
5    69.223478   0.687792  11.108696
6    60.142308   0.150054  12.980769
7    40.141176   0.150399  26.705882
8    67.350000   0.371410   6.250000
24   89.805303  12.759291   0.000000
All  68.574901   3.613524  11.363636

##### .loc .iloc 方法選擇

In [0]:
df_p.iloc[-1, 1]

3.6135235573122535

In [0]:
df_p.loc['All','crim']

3.6135235573122535

##### 使用布林值篩選

In [0]:
df_p.loc[df_p.age > 60]

age       crim         zn
rad                                 
2    64.770833   0.083285  20.416667
4    60.841818   0.393903  14.731818
5    69.223478   0.687792  11.108696
6    60.142308   0.150054  12.980769
8    67.350000   0.371410   6.250000
24   89.805303  12.759291   0.000000
All  68.574901   3.613524  11.363636